-- 코드를 입력하세요
-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, 
        SUM(s.SALES * b.PRICE) as TOTAL_SALES
FROM BOOK_SALES s
    JOIN BOOK b
    ON b.BOOK_ID = s.BOOK_ID
    JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE s.SALES_DATE LIKE '2022-01%'
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC